version: 2
updates:
    - package-ecosystem: npm
      directories: '**/*'
      schedule:
          interval: weekly
          time: '10:00'
          timezone: Europe/Berlin
      open-pull-requests-limit: 15
      assignees:
          - oweitman
      versioning-strategy: increase

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: weekly
          time: '10:00'
          timezone: Europe/Berlin
      open-pull-requests-limit: 15
      assignees:
          - oweitman
